In [9]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [10]:
er_train_df = pd.read_csv('../Data/Training.csv')
er_test_df = pd.read_csv('../Data/Testing.csv')
er_df = pd.concat([er_train_df,er_test_df])
er_df.head()

id        d0        d1        d2        d3        d4        d5  \
0  10118481  0.380106  0.348021  0.299160  0.250793  0.254492  0.240445   
1  10120469  0.311002  0.272447  0.231935  0.185900  0.199802  0.198825   
2  10131352       NaN       NaN       NaN       NaN       NaN       NaN   
3  10161559  0.284867  0.249970  0.193271  0.138756  0.152207  0.172866   
4   1021836  0.377440  0.342185  0.287144  0.223227  0.198685  0.200168   

         d6        d7        d8  ...       d51       d52       d53       d54  \
0  0.208501  0.241401  0.263303  ...  0.164181  0.112841  0.046555  0.053474   
1  0.191371  0.220092  0.230186  ...  0.161576  0.103059  0.079105  0.088599   
2       NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN   
3  0.140559  0.169266  0.171820  ...  0.183529  0.111915  0.094234  0.128893   
4  0.221059  0.284502  0.341772  ...  0.217035  0.155439  0.156955  0.220011   

        d55       d56       d57       d58       d59  class  
0  0.202719  0.135361  0.086261  0.116328  0.100941  Angry  
1  0.171182  0.114073  0.041964  0.085051  0.077860  Angry  
2       NaN       NaN       NaN       NaN       NaN  Angry  
3  0.156798  0.115935  0.021351  0.113588  0.068529  Angry  
4  0.182061  0.095076  0.100465  0.121072  0.120199  Angry  

[5 rows x 62 columns]

In [11]:
er_df.shape

(35887, 62)

In [12]:
er_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35887 entries, 0 to 7177
Data columns (total 62 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   id      35887 non-null  int64  
 1   d0      33121 non-null  float64
 2   d1      33121 non-null  float64
 3   d2      33121 non-null  float64
 4   d3      33121 non-null  float64
 5   d4      33121 non-null  float64
 6   d5      33121 non-null  float64
 7   d6      33121 non-null  float64
 8   d7      33121 non-null  float64
 9   d8      33121 non-null  float64
 10  d9      33121 non-null  float64
 11  d10     33121 non-null  float64
 12  d11     33121 non-null  float64
 13  d12     33121 non-null  float64
 14  d13     33121 non-null  float64
 15  d14     33121 non-null  float64
 16  d15     33121 non-null  float64
 17  d16     33121 non-null  float64
 18  d17     33121 non-null  float64
 19  d18     33121 non-null  float64
 20  d19     33121 non-null  float64
 21  d20     33121 non-null  float64
 22 

In [13]:
# er_df['mouth_height_to_width_ratio']=er_df['mouth_height']/er_df['mouth_width']
# er_df = er_df.drop(columns=['mouth_height','mouth_width'], axis=1)
# er_df.head()

In [14]:
# er_df['eyes_height_to_width_ratio_avg']=((er_df['left_eye_height']/er_df['left_eye_width'])+(er_df['right_eye_height']/er_df['right_eye_width']))/2
# er_df = er_df.drop(columns=['left_eye_height','left_eye_width','right_eye_height','right_eye_width'], axis=1)
# er_df.head()

In [15]:
# er_df['upper_to_lower_lips_thickness_ratio']=(er_df['upper_lip_thickness']/er_df['lower_lip_thickness'])
# er_df = er_df.drop(columns=['upper_lip_thickness','lower_lip_thickness'], axis=1)
# er_df.head()

In [16]:
# er_df['mouth_to_eyes_avg']=(er_df['left_mouth_to_eye']+er_df['right_mouth_to_eye'])/2
# er_df = er_df.drop(columns=['left_mouth_to_eye','right_mouth_to_eye'], axis=1)
# er_df.head()

In [17]:
# er_df['outer_brows_to_outer_eyes_avg']=(er_df['left_brow_to_eye_left']+er_df['right_brow_to_eye_right'])/2
# er_df = er_df.drop(columns=['left_brow_to_eye_left','right_brow_to_eye_right'], axis=1)
# er_df.head()

In [18]:
# er_df['middle_brows_to_outer_eyes_avg']=(er_df['left_brow_to_eye_middle']+er_df['right_brow_to_eye_middle'])/2
# er_df = er_df.drop(columns=['left_brow_to_eye_middle','right_brow_to_eye_middle'], axis=1)
# er_df.head()

In [19]:
# er_df['inner_brows_to_outer_eyes_avg']=(er_df['left_brow_to_eye_right']+er_df['right_brow_to_eye_left'])/2
# er_df = er_df.drop(columns=['left_brow_to_eye_right','right_brow_to_eye_left'], axis=1)
# er_df.head()

In [20]:
# er_df['brow_to_brow_to_brows_to_nose_ration']=er_df['brow_to_brow']/er_df['brows_to_nose']
# er_df = er_df.drop(columns=['brow_to_brow','brows_to_nose'], axis=1)
# er_df.head()

In [21]:
# sns.countplot(er_df['class'],order = er_df['class'].value_counts(normalize=True).index)

In [22]:
# er_df = er_df.drop(columns='id')
er_df.head()

id        d0        d1        d2        d3        d4        d5  \
0  10118481  0.380106  0.348021  0.299160  0.250793  0.254492  0.240445   
1  10120469  0.311002  0.272447  0.231935  0.185900  0.199802  0.198825   
2  10131352       NaN       NaN       NaN       NaN       NaN       NaN   
3  10161559  0.284867  0.249970  0.193271  0.138756  0.152207  0.172866   
4   1021836  0.377440  0.342185  0.287144  0.223227  0.198685  0.200168   

         d6        d7        d8  ...       d51       d52       d53       d54  \
0  0.208501  0.241401  0.263303  ...  0.164181  0.112841  0.046555  0.053474   
1  0.191371  0.220092  0.230186  ...  0.161576  0.103059  0.079105  0.088599   
2       NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN   
3  0.140559  0.169266  0.171820  ...  0.183529  0.111915  0.094234  0.128893   
4  0.221059  0.284502  0.341772  ...  0.217035  0.155439  0.156955  0.220011   

        d55       d56       d57       d58       d59  class  
0  0.202719  0.135361  0.086261  0.116328  0.100941  Angry  
1  0.171182  0.114073  0.041964  0.085051  0.077860  Angry  
2       NaN       NaN       NaN       NaN       NaN  Angry  
3  0.156798  0.115935  0.021351  0.113588  0.068529  Angry  
4  0.182061  0.095076  0.100465  0.121072  0.120199  Angry  

[5 rows x 62 columns]

In [23]:
# for x in er_df['class'].unique():
#     print(x)
#     print(er_df[er_df['class']==x]['mouth_height_to_width_ratio'].mean())

In [24]:
# df_num = er_df[er_df['class']=='Angry'].select_dtypes(include = ['float64', 'int64'])
# df_num.hist(figsize=(10, 10), bins=50, xlabelsize=8, ylabelsize=8)

In [25]:
# columns = [x for x in er_df.columns[1:]]
# Emotions_Colors = {'Angry':'red', 'Happy':"green", 'Fear':'yellow', 'Sad':'blue', 'Neutral':'gray', 'Surprised':'orange', 'Disgusted':'purple'}
# for col in columns:
#     fig, ax = plt.subplots()
#     for x in Emotions_Colors:
#         sns.kdeplot(er_df[er_df["class"]==x][col], shade=True, color=Emotions_Colors[x], label="Angry", ax=ax)
#     ax.set_xlabel(col)
#     ax.set_ylabel("Density")
#
#
#

In [26]:
# for i in range(0, len(er_df.columns), 5):
#     sns.pairplot(data=er_df,
#                  x_vars=er_df.columns[i:i+5],
#                  y_vars=['class'],
#                  )


In [27]:
# corr = df_num.corr() # We already examined SalePrice correlations
# plt.figure(figsize=(20,20))
#
# sns.heatmap(corr[(corr >= 0.5) | (corr <= -0.4)],
#             cmap='viridis', vmax=1.0, vmin=-1.0, linewidths=0.1,
#             annot=True, annot_kws={"size": 8}, square=True);

In [28]:
# def ratio(df,classes):
#     for i in classes:
#         nulls = df[df.isnull().any(axis=1)]
#         print(i, ' : ', len(nulls[nulls['class'] == i]), ' rows are NULL out of ', len(df[df['class'] == i]), ' rows → ', 100 * len(nulls[nulls['class'] == i]) / len(df[df['class'] == i]), '%')
#
# ratio(er_df,er_df['class'].unique())

In [29]:
# er_df.describe()

In [30]:
# er_df.groupby('class').mean()

### Displaying Your Correlation Matrix

In [31]:
# def plot_corr(df,size=20):
#
#     corr = df.corr()
#     fig, ax = plt.subplots(figsize=(size, size))
#     ax.legend()
#     cax = ax.matshow(corr)
#     fig.colorbar(cax)
#     plt.xticks(range(len(corr.columns)), corr.columns, rotation='vertical')
#     plt.yticks(range(len(corr.columns)), corr.columns)
#
# plot_corr(er_df)

## Preparing out  Dataset for ML

In [32]:
# er_df.describe()

In [33]:
# # er_df = er_df.drop(['id'],axis=1)
# # new_er_df = er_df.drop(['id'],axis=1)
# # for x in new_er_df.columns:
# #     q0=range(er_df[x].quantile(0),er_df[x].quantile(0.25),0.000000001)
# #     q1=range(er_df[x].quantile(0.25),er_df[x].quantile(0.5))
# #     q2=range(er_df[x].quantile(0.5),er_df[x].quantile(0.75))
# #     q3=range(er_df[x].quantile(0.75),er_df[x].quantile(1))
# #
# #     # if 0 < new_er_df[x] < er_df[x].quantile(0.25):
# #     #     new_er_df[x] = 1
# #     # # new_er_df[x] = np.where(er_df[x].quantile(0.25) <= er_df[x] < er_df[x].quantile(0.5), 1,2)
# #     # # new_er_df[x] = np.where(er_df[x].quantile(0.5) <= er_df[x] < er_df[x].quantile(0.75), 2,3)
# #     # new_er_df[x] = np.where(er_df[x].quantile(0.75) <= er_df[x] < er_df[x].quantile(1), 3,4)
# new_er_df.describe()

In [34]:
# er_df.fillna(er_df.mean(), inplace=True)
# new_er_df = er_df.drop(['id'],axis=1)
# for x in new_er_df.columns[:-1]:
#     for i in range(100):
#         new_er_df[x][(new_er_df[x]>=er_df[x].quantile(i/100)) & (new_er_df[x]<er_df[x].quantile((i+1)/100))] = i
# er_df = new_er_df

## Preparing our Dataset for Machine Learning

In [35]:
from sklearn.preprocessing import LabelEncoder

# er_df = er_df.dropna(axis=0, subset=['d48'])
er_df = er_df.drop(['id'],axis=1)
#
#
labelencoder = LabelEncoder()
er_df['class'] = labelencoder.fit_transform(er_df['class'])
er_df.head(100)

# categorial = ['class']
# er_df = pd.get_dummies(er_df, columns=categorial)

d0        d1        d2        d3        d4        d5        d6  \
0   0.380106  0.348021  0.299160  0.250793  0.254492  0.240445  0.208501   
1   0.311002  0.272447  0.231935  0.185900  0.199802  0.198825  0.191371   
2        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3   0.284867  0.249970  0.193271  0.138756  0.152207  0.172866  0.140559   
4   0.377440  0.342185  0.287144  0.223227  0.198685  0.200168  0.221059   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.390988  0.349935  0.317614  0.263042  0.276332  0.284854  0.279467   
96  0.369993  0.324752  0.269125  0.210827  0.224736  0.222158  0.217633   
97  0.353007  0.322551  0.295687  0.244856  0.255100  0.267501  0.260225   
98  0.447748  0.400621  0.346027  0.276598  0.285942  0.273743  0.283970   
99  0.377280  0.341048  0.296497  0.236021  0.229281  0.238362  0.248162   

          d7        d8        d9  ...       d51       d52       d53       d54  \
0   0.241401  0.263303  0.297498  ...  0.164181  0.112841  0.046555  0.053474   
1   0.220092  0.230186  0.249336  ...  0.161576  0.103059  0.079105  0.088599   
2        NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN   
3   0.169266  0.171820  0.210176  ...  0.183529  0.111915  0.094234  0.128893   
4   0.284502  0.341772  0.375194  ...  0.217035  0.155439  0.156955  0.220011   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.341382  0.388164  0.429656  ...  0.141496  0.078040  0.108057  0.201776   
96  0.262835  0.292034  0.323926  ...  0.216846  0.136956  0.111812  0.159105   
97  0.323595  0.380316  0.423984  ...  0.148575  0.129971  0.152336  0.218769   
98  0.347823  0.390250  0.428632  ...  0.237176  0.137886  0.148629  0.214727   
99  0.310602  0.366165  0.403148  ...  0.175835  0.126003  0.135520  0.193490   

         d55       d56       d57       d58       d59  class  
0   0.202719  0.135361  0.086261  0.116328  0.100941      0  
1   0.171182  0.114073  0.041964  0.085051  0.077860      0  
2        NaN       NaN       NaN       NaN       NaN      0  
3   0.156798  0.115935  0.021351  0.113588  0.068529      0  
4   0.182061  0.095076  0.100465  0.121072  0.120199      0  
..       ...       ...       ...       ...       ...    ...  
95  0.222987  0.097596  0.125273  0.106331  0.113713      0  
96  0.183178  0.129064  0.045977  0.102985  0.091534      0  
97  0.238864  0.084082  0.143073  0.133218  0.131186      0  
98  0.258505  0.158207  0.107690  0.143943  0.150906      0  
99  0.214912  0.078470  0.120060  0.114204  0.123671      0  

[100 rows x 61 columns]

In [36]:
# y = []
# for x in er_df.columns:
#     if er_df[x].nunique()==2:
#         y.append(x)
# y

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

er_df = shuffle(er_df)

er_df.fillna(er_df.mean(), inplace=True)

from imblearn.over_sampling import SMOTE
SMOTE = SMOTE(random_state=888)
X_resampled, y_resampled = SMOTE.fit_resample(er_df.drop(['class'],axis=1),er_df['class'])

# categorial = ['class_Angry', 'class_Disgust', 'class_Fear', 'class_Happy', 'class_Neutral', 'class_Sad', 'class_Surprise']

# X_resampled, y_resampled = RandomUnderSampler.fit_resample(er_df.drop(categorial,axis=1),er_df['class_Neutral'])

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.3,shuffle=True)

# Normalize the data
from sklearn.preprocessing import StandardScaler
#
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)
# ems = ['class_Disgust','class_Fear','class_Happy','class_Neutral','class_Sad','class_Surprise','class_Angry']
# print('1/0')
# print(er_df.shape[0]/7)
# for x in ems:
#
# print(em, er_df[er_df[em] ==1].shape[0],'/',er_df[er_df[em] ==0].shape[0])
# print(em, er_df_temp[er_df_temp[em] ==1].shape[0],'/',er_df_temp[er_df_temp[em] ==0].shape[0])
# print(em, X_resampled.shape,er_df_temp[er_df_temp[em] ==0].shape[0])

In [38]:
# from sklearn.model_selection import cross_val_score
# from sklearn.pipeline import make_pipeline
# from sklearn.preprocessing import StandardScaler
# from sklearn.svm import SVC
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import StratifiedKFold
# #
# # Create an instance of Pipeline
# #
# pipeline = make_pipeline(StandardScaler(), RandomForestClassifier())
# #
# # Create an instance of StratifiedKFold which can be used to get indices of different training and test folds
# #
# strtfdKFold = StratifiedKFold(n_splits=10)
# kfold = strtfdKFold.split(X_train, y_train)
# scores = []
# #
# #
# #
# for k, (train, test) in enumerate(kfold):
#     pipeline.fit(X_train.iloc[train, :], y_train.iloc[train])
#     score = pipeline.score(X_train.iloc[test, :], y_train.iloc[test])
#     scores.append(score)
#     print('Fold: %2d, Training/Test Split Distribution: %s, Accuracy: %.3f' % (k+1, np.bincount(y_train.iloc[train]), score))
#
# print('\n\nCross-Validation accuracy: %.3f +/- %.3f' %(np.mean(scores), np.std(scores)))

### Let's Try a Random Forest Classifer

In [39]:
from sklearn.ensemble import RandomForestClassifier



model = RandomForestClassifier()
# parameters = {
#     "n_estimators":[5,10,50,100,250],
#     "max_depth":[2,4,8,16,32,None]
#
# }
#
# from sklearn.model_selection import GridSearchCV
# cv = GridSearchCV(model,parameters,cv=5)
# cv.fit(X_train,y_train.values.ravel())

model.fit(X_train, y_train)

predictions = model.predict(X_test)
score = model.score(X_test, y_test)

print("Accuracy {0:.2f}%".format(100*accuracy_score(predictions, y_test)))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy 71.25%
[[1683  376   71  114  218  163   60]
 [   2 2693    1    0   11    6    2]
 [ 163  340 1406   99  243  226  215]
 [  90  112   64 2043  177   85   67]
 [ 143  125  101  122 1870  299   86]
 [ 164  356  105  138  415 1478   56]
 [  45  155   42   50   76   45 2276]]
              precision    recall  f1-score   support

           0       0.73      0.63      0.68      2685
           1       0.65      0.99      0.78      2715
           2       0.79      0.52      0.63      2692
           3       0.80      0.77      0.79      2638
           4       0.62      0.68      0.65      2746
           5       0.64      0.54      0.59      2712
           6       0.82      0.85      0.84      2689

    accuracy                           0.71     18877
   macro avg       0.72      0.71      0.71     18877
weighted avg       0.72      0.71      0.71     18877



## Save Model and History

In [41]:
import joblib

joblib.dump(model, "./fer2013_model.joblib")

['./fer2013_model.joblib']